TableView -> eigene Klasse -> Funktioniert jedoch nicht ->
Juni 23, 2022 6:14:14 PM javafx.scene.control.cell.PropertyValueFactory getCellDataReflectively
WARNUNG: Can not retrieve property 'ausgabenListID' in PropertyValueFactory: javafx.scene.control.cell.PropertyValueFactory@24b7549d with provided class type: class modelclasses.Ausgaben
java.lang.RuntimeException: java.lang.IllegalAccessException: module javafx.base cannot access class modelclasses.Ausgaben (in module com.example.finanzmanager_java) because module com.example.finanzmanager_java does not open modelclasses to javafx.base
	at javafx.base@18-ea/com.sun.javafx.property.PropertyReference.get(PropertyReference.java:173)
	at javafx.controls@18-ea/javafx.scene.control.cell.PropertyValueFactory.getCellDataReflectively(PropertyValueFactory.java:184)
	at javafx.controls@18-ea/javafx.scene.control.cell.PropertyValueFactory.call(PropertyValueFactory.java:154)
	at javafx.controls@18-ea/javafx.scene.control.cell.PropertyValueFactory.call(PropertyValueFactory.java:133)
	at javafx.controls@18-ea/javafx.scene.control.TableColumn.getCellObservableValue(TableColumn.java:592)
	at javafx.controls@18-ea/javafx.scene.control.TableColumn.getCellObservableValue(TableColumn.java:577)
	at javafx.controls@18-ea/javafx.scene.control.TableCell.updateItem(TableCell.java:680)
	at javafx.controls@18-ea/javafx.scene.control.TableCell.indexChanged(TableCell.java:484)
	at javafx.controls@18-ea/javafx.scene.control.IndexedCell.updateIndex(IndexedCell.java:120)
	at javafx.controls@18-ea/javafx.scene.control.skin.TableRowSkinBase.updateCells(TableRowSkinBase.java:539)
	at javafx.controls@18-ea/javafx.scene.control.skin.TableRowSkinBase.<init>(TableRowSkinBase.java:159)
	at javafx.controls@18-ea/javafx.scene.control.skin.TableRowSkin.<init>(TableRowSkin.java:89)
	at javafx.controls@18-ea/javafx.scene.control.TableRow.createDefaultSkin(TableRow.java:213)